### ISSUE TITLE
daitnu.com 도메인끼리는 메일 송수신 시 DB 저장 안됨

### ISSUE THREAD

**Issue by BuildTheTruth** [connect-foundation/2019-06#114]
stmp 서버에 파일로 저장은 되지만 postfix hook이 발생하지 않아 DB에 저장되지 않는 버그 발생

**Comment by sjh2428** [comment]
Advanced Content Filter using Postfix를 찾아보새오

**Comment by sjh2428** [comment]
Python을 활용하여 고침
