### ISSUE TITLE
메일 전송시 메일 템플릿이 2개가 생기는 문제

### ISSUE THREAD

**Issue by ljh1324** [connect-foundation/2019-06#198]
1. 메일을 전송할 경우 데이터베이스에 메일 템플릿이 2개가 생겨남
2. 2개의 메일 템플릿은 create_at(updated_at) 시간이 9시간 정도 차이가 남
3. 2개의 메일 템플릿 중 하나의 메일 템플릿은 mail_template_id를 가지고 있는 mail이 존재하지 않음

**Comment by sjh2428** [comment]
현재 메일을 전송할 때 BE에서 한번, SMTP서버 훅스에서 한번 이렇게 저장되어 두번 저장되는 것으로 보입니다.
이를 해결하기 위해 훅스의 발동 조건을 알아야 하는데, 훅스는 현재 외부 메일서버로 보낼 경우 한번, 로컬 메일서버로 보낼 때도 한번 발생하는 것으로 보입니다.
이를 토대로 해결 방법을 생각해 본 결과 BE에서 메일의 데이터를 DB에 insert 하지 말고 훅스 내에서 from과 to를 판별하여 from에 적혀있는 이메일의 도메인이 daitnu.com이라면 해당 사용자의 보낸 메일이라 판별하여 DB에 insert하고, to에 적혀있는 이메일의 도메인이 daitnu.com이라면 해당 유저가 받은 메일이라 판별하여 DB에 insert하면 될 듯 합니다.
