### ISSUE TITLE
postfix의 25번 포트를 닫을 경우 dovecot을 통해 메시지를 받지 못함

### ISSUE THREAD

**Issue by ljh1324** [connect-foundation/2019-06#25]
mailin을 통해 메일을 받아 db에 저장은 가능하나 dovecot을 통해 메시지를 받지 못할 경우 pop, imap 서비스를 하지 못하는 문제 발생

예상해결방안)
1. mailin을 통해 메시지를 받은 후 유저가 있는지 확인 후 적절한 메일함에 다시 메일을 작성?

2. postfix에서 25번 포트를 열어놓고 dovecot으로 메일을 받은 후 웹서버에서 회원이 메일을 요청시 dovecot의 pop, imap 서비스를 이용하여 메일을 받아와 db에 등록 후 회원에게 보여줌?

3. postfix의 `content_filter`를 사용하여 메일을 처리하도록 할 수 있도록 할 수도 있는 것 같음. [StackOverflow 참고](https://stackoverflow.com/questions/1778562/postfix-message-received-hook)

**Comment by sjh2428** [comment]
3번 해결방안으로 하는 것이 좋은 방안인 것으로 판단되어 [블로그](https://lloydrochester.com/postfix/mysql/dovecot/script/2019/04/27/process-mail-script-postfix.html), [postfix 공식문서](http://www.postfix.org/FILTER_README.html#simple_filter)를 참조하여 메일이 들어올 때 쉘 프로그램을 실행하는 방향으로 테스트 및 구현 완료
