### ISSUE TITLE
데이터베이스 설계

### ISSUE THREAD

**Issue by ljh1324** [connect-foundation/2019-06#3]
메일 시스템에 필요한 데이터베이스 설계

**Comment by jonghwajoa** [comment]
1차 설계
![1차설계](https://user-images.githubusercontent.com/31912670/68567460-64286680-049c-11ea-9154-f759d2099b86.jpg)

**Comment by jonghwajoa** [comment]
2차 설계
![db 2차설계](https://user-images.githubusercontent.com/31912670/68735437-f5c0e100-0620-11ea-86fe-8a228da47140.png)

**Comment by jonghwajoa** [comment]
4차 설계
![DB4차설계](https://user-images.githubusercontent.com/31912670/69478970-a3ab6700-0e3b-11ea-9ff5-92be8c8e5c10.jpg)

**Comment by ljh1324** [comment]
5차 설계
![DB설계](https://i.imgur.com/nTZ6oyc.png)

**Comment by jonghwajoa** [comment]
attachment content를 url로 변경

![6차설계](https://user-images.githubusercontent.com/31912670/69939433-2f4f8280-1523-11ea-9ec7-51f62b803ce6.jpg)
