### ISSUE TITLE
[Bug] 메일함에서의 버그(?)

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-06#312]
버그는 아니지만, 메일함에서 
메일에 마우스를 hover하면 밑줄이 떠서 링크인줄알았는데 아무런 액션이 없네요 👀 
아직 기능개발이 안된것이라 생각합니다!

![image](https://user-images.githubusercontent.com/28642472/70300199-3c79b380-183a-11ea-8bad-67069757df78.png)

**Comment by BuildTheTruth** [comment]
딩동댕
