### ISSUE TITLE
[BUG] 휴지통 내에서의 시간정렬 오류 

### ISSUE THREAD

**Issue by KKambi** [connect-foundation/2019-06#313]
![휴지통 시간정렬이 이상해요](https://user-images.githubusercontent.com/37494867/70300366-a98d4900-183a-11ea-961e-2a7b896c167d.jpg)

- 전체메일함 내에서는 잘 되는데, 휴지통 내에서는 시간정렬/시간역정렬 안되는 것 같아요.
- 제목 정렬은 잘 되더라구요!

**Comment by jonghwajoa** [comment]
감사합니다. 
해당 bug는 fix했습니다.
