### ISSUE TITLE
[BUG] 로그인 이후 라우팅/히스토리 문제

### ISSUE THREAD

**Issue by KKambi** [connect-foundation/2019-06#315]
![로그인하고 뒤로가면 로그인화면](https://user-images.githubusercontent.com/37494867/70300407-c7f34480-183a-11ea-94ce-b55c6bc85c12.jpg)
- 로그인하고 뒤로가면 로그인화면이 또 나와요!
- 다시 로그인하면 정상적으로 작동합니다.

**Comment by jonghwajoa** [comment]
의도된 사항입니다.
