### ISSUE TITLE
[Bug] 첨부파일 업로드

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-06#317]
첨부파일 업로드 할 시에 몇가지 버그가 있습니다.
- 첨부파일을 다시 업로드 했을 때 추가가 되지 않음
- md 파일 업로드 안됨

추가적으로 허용되는 파일 형식과 용량을 적어주시면 좋을 것 같아요.

한주동안 고생하셨씁니다.

**Comment by jonghwajoa** [comment]
- [ ] 첨부파일을 다시올리면 기존 첨부파일이 사라진다.
- [ ] md 파일업로드가 안된다.
- [ ] 허용되는 파일 형식을 알려준다.
- [ ] 허용 용량을 알려준다.

**Comment by jonghwajoa** [comment]
반영했습니다.

해당 버그와, 기능개선은 릴리즈 0.2.0에 배포될 예정입니다.
