### ISSUE TITLE
[Bug] Footer가 잘려서 보여짐

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-06#319]
<img width="908" alt="스크린샷 2019-12-06 오후 3 15 39" src="https://user-images.githubusercontent.com/22005861/70300619-4cde5e00-183b-11ea-9cdb-8957598156ec.png">

창 높이가 작을 때 Footer가 잘려서 보여집니다.

**Comment by jonghwajoa** [comment]
fix했습니다.
다음 릴리즈에 반영될것입니다.
감사합니다.
