### ISSUE TITLE
[Bug] 404 Error 

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-06#323]
<img width="1131" alt="스크린샷 2019-12-06 오후 3 18 04" src="https://user-images.githubusercontent.com/22005861/70300743-aa72aa80-183b-11ea-800e-8b1a2626e2db.png">

메일 쓰기 시에 404 Error가 발생합니다.

**Comment by jonghwajoa** [comment]
같은 상황을 시뮬레이션 했을때 404가 뜨지 않았습니다.
메일을 읽고 메일쓰기를 한것이 아닌지 생각됩니다.
해당 부분은 의도된 상황입니다.
