### ISSUE TITLE
[Bug] 중복되는 메일함 생성 가능

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-06#326]
<img width="295" alt="스크린샷 2019-12-06 오후 3 22 00" src="https://user-images.githubusercontent.com/22005861/70300910-32f14b00-183c-11ea-8f95-c9cf2182ade9.png">

원래는 메일함이 중복되면 안되는것  같은데..
메일함을 추가했다가 이름변경하면 중복되는 이름의 메일함이 잘 만들어집니다..

**Comment by sjh2428** [comment]
감사합니다 fix하였습니다.
