### ISSUE TITLE
[Bug] 메일함 추가하기 버그

### ISSUE THREAD

**Issue by dobest27** [connect-foundation/2019-06#327]
<img width="290" alt="스크린샷 2019-12-06 오후 3 27 48" src="https://user-images.githubusercontent.com/6308222/70301164-f83be280-183c-11ea-966b-6ea74ae31c6c.png">
<img width="257" alt="스크린샷 2019-12-06 오후 3 24 20" src="https://user-images.githubusercontent.com/6308222/70301064-ad21cf80-183c-11ea-8ddc-1ce713e1ae7e.png">

- 메일함 추가하기에서 추가 버튼을 빠른 시간 안에 여러번 여러개 만들어집니다
- 더 빠르게 하니 서버가 죽었습니다

테스트 환경 : chrome 최신

**Comment by sjh2428** [comment]
감사합니다 fix하였습니다.
