### ISSUE TITLE
[Bug] 로그아웃 눌렀을때, 로그아웃 안되고 메일페이지로 가짐

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-06#343]
버튼의 바깥쪽도 클릭이되는데, 이때 로그아웃이 안되고 메일페이지로 이동함

![image](https://user-images.githubusercontent.com/31912670/70374642-f440bb00-1937-11ea-8d37-d2228faef4f5.png)

**Comment by ljh1324** [comment]
#350
