### ISSUE TITLE
[BE/Infra] Elastic Search 조사 / 학습

### ISSUE THREAD

**Issue by sjh2428** [connect-foundation/2019-06#369]

**Comment by jonghwajoa** [comment]
조사는 했으나, 도입여부는 아직 불문명함.
이유 :
1. 시간이 부족할 수 있다.
 - 이시간을 다른 부족한것을 넣을 것인가?
2. ES를 사용안하면 성능이 어떤지부터 측정해봐야한다.

-> 즉 DB검색을 통해 구현을 선행한다.
