### ISSUE TITLE
[Refactoring] 기존 코드 개선 해야할 것들 

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-06#412]
# 차선에 만족했던 코드들 적어주세요.
- [x] 휴지통 category를 db search하지 않고, usertable에 저장
- [x] attachment service 계층 공통 로직 함수분리
- [ ] 파일다운로드 퍼센트 제공
- [x] `node-imap` Promisify
- [x] 회원가입시 에러 메시지 내용에 따라 표시 위치 결정되는 것
- [ ] css제거할 수 없는가?
- [x] 메일 읽기에서 첨부파일 있을때만 Request

**Comment by jonghwajoa** [comment]
> # 차선에 만족했던 코드들 적어주세요.
> * [x]  휴지통 category를 db search하지 않고, usertable에 저장
> * [x]  attachment service 계층 공통 로직 함수분리
> * [ ]  파일다운로드 퍼센트 제공
> * [ ]  `node-imap` Promisify
> * [ ]  회원가입시 에러 메시지 내용에 따라 표시 위치 결정되는 것
> * [ ]  css제거할 수 없는가?

**Comment by sjh2428** [comment]
> > # 차선에 만족했던 코드들 적어주세요.
> > 
> > * [x]   휴지통 category를 db search하지 않고, usertable에 저장
> > * [x]   attachment service 계층 공통 로직 함수분리
> > * [ ]   파일다운로드 퍼센트 제공
> > * [x]   `node-imap` Promisify
> > * [ ]   회원가입시 에러 메시지 내용에 따라 표시 위치 결정되는 것
> > * [ ]   css제거할 수 없는가?

**Comment by jonghwajoa** [comment]
> # 차선에 만족했던 코드들 적어주세요.
> * [x]  휴지통 category를 db search하지 않고, usertable에 저장
> * [x]  attachment service 계층 공통 로직 함수분리
> * [ ]  파일다운로드 퍼센트 제공
> * [x]  `node-imap` Promisify
> * [ ]  회원가입시 에러 메시지 내용에 따라 표시 위치 결정되는 것
> * [ ]  css제거할 수 없는가?
> * [ ]  메일 읽기에서 첨부파일 있을때만 Request

**Comment by ljh1324** [comment]
> > # 차선에 만족했던 코드들 적어주세요.
> > 
> > * [x]   휴지통 category를 db search하지 않고, usertable에 저장
> > * [x]   attachment service 계층 공통 로직 함수분리
> > * [ ]   파일다운로드 퍼센트 제공
> > * [x]   `node-imap` Promisify
> > * [x]   회원가입시 에러 메시지 내용에 따라 표시 위치 결정되는 것
> > * [ ]   css제거할 수 없는가?
> > * [x]   메일 읽기에서 첨부파일 있을때만 Request
