### ISSUE TITLE
화면 기획서 작성

### ISSUE THREAD

**Issue by BuildTheTruth** [connect-foundation/2019-06#6]
- 구글 프레젠테이션으로 작성
- 개발 단계에서 팀원 사이의 이견이 생기지 않도록 기능을 명확히 정의한다. 또한, 필수적인 동작 사항에 대한 설명을 반드시 포함해햐아 한다. 기능 정의와 동작 설명의 수준은 부스트캠프 학습 스프린트의 기획서를 참고
- 기능 목록의 모든 요소를 화면 기획서에서 확인 가능해야 함
- 디자인적인 미려함을 고려하지 않아도 된다.
- 하위 기능을 변경할 경우 화면 기획서를 업데이트하고 모든 업데이트 이력은 기획서 내 별도의 슬라이드에 기록
- Day4 19:00 까지 1차 작성을 완료하고 URL을 공유한다. 기획 발표 이후 피드백을 반영하여 Day5 19:00까지 2차 작성을 완료

**Comment by jonghwajoa** [comment]
https://docs.google.com/presentation/d/1K3e6DtXNuTWa83kgli_PFtIaOi6VpfCDOspjwK8VUXQ/edit?usp=sharing
