### ISSUE TITLE
프로토타입

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-06#7]
기술적으로 구현이 가능한지 확인해봅니다.

불가능 하다면, 기획을 다시 해야하고,
가능하다면, 어떤 부분을 더 고민해봐야 하는지 확인합니다.

- [x] 메일서버 구축
- [x] 메일 받기
- [x] 메일 보내기
- [x] 받은 메일 파싱
- [x] dns설정
- [x] tls
- [x] Mail Account DB연동
- [x] 메일 서버로 메일이 왔을 때 DB에 등록
- [x] 주소록 검색알고리즘
- [x] dovecot pop3, imap server연결

**Comment by sjh2428** [comment]
> 기술적으로 구현이 가능한지 확인해봅니다.
> 
> 불가능 하다면, 기획을 다시 해야하고,
> 가능하다면, 어떤 부분을 더 고민해봐야 하는지 확인합니다.
> 
> * [x]  메일서버 구축
> * [ ]  메일 받기
> * [x]  메일 보내기
> * [ ]  받은 메일 파싱
> * [ ]  dns설정
> * [ ]  tls
> * [ ]  Mail Account DB연동
> * [ ]  메일 서버로 메일이 왔을 때 DB에 등록하는 crontab 작성

**Comment by jonghwajoa** [comment]
> > 기술적으로 구현이 가능한지 확인해봅니다.
> > 불가능 하다면, 기획을 다시 해야하고,
> > 가능하다면, 어떤 부분을 더 고민해봐야 하는지 확인합니다.
> > 
> > * [x]   메일서버 구축
> > * [x]   메일 받기
> > * [x]   메일 보내기
> > * [ ]   받은 메일 파싱
> > * [x]   dns설정
> > * [ ]   tls
> > * [ ]   Mail Account DB연동
> > * [ ]   메일 서버로 메일이 왔을 때 DB에 등록하는 crontab 작성

**Comment by BuildTheTruth** [comment]
> > > 기술적으로 구현이 가능한지 확인해봅니다.
> > > 불가능 하다면, 기획을 다시 해야하고,
> > > 가능하다면, 어떤 부분을 더 고민해봐야 하는지 확인합니다.
> > > 
> > > * [x]    메일서버 구축
> > > * [x]    메일 받기
> > > * [x]    메일 보내기
> > > * [ ]    받은 메일 파싱
> > > * [x]    dns설정
> > > * [ ]    tls
> > > * [ ]    Mail Account DB연동
> > > * [ ]    메일 서버로 메일이 왔을 때 DB에 등록하는 crontab 작성

**Comment by ljh1324** [comment]
> > > > 기술적으로 구현이 가능한지 확인해봅니다.
> > > > 불가능 하다면, 기획을 다시 해야하고,
> > > > 가능하다면, 어떤 부분을 더 고민해봐야 하는지 확인합니다.
> > > > 
> > > > * [x]     메일서버 구축
> > > > * [x]     메일 받기
> > > > * [x]     메일 보내기
> > > > * [x]     받은 메일 파싱
> > > > * [x]     dns설정
> > > > * [x]     tls
> > > > * [ ]     Mail Account DB연동
> > > > * [ ]     메일 서버로 메일이 왔을 때 DB에 등록하는 crontab 작성

**Comment by BuildTheTruth** [comment]
> 기술적으로 구현이 가능한지 확인해봅니다.
> 
> 불가능 하다면, 기획을 다시 해야하고,
> 가능하다면, 어떤 부분을 더 고민해봐야 하는지 확인합니다.
> 
> * [x]  메일서버 구축
> * [x]  메일 받기
> * [x]  메일 보내기
> * [x]  받은 메일 파싱
> * [x]  dns설정
> * [x]  tls
> * [x]  Mail Account DB연동
> * [ ]  메일 서버로 메일이 왔을 때 DB에 등록
> * [ ]  주소록 검색알고리즘

**Comment by jonghwajoa** [comment]
> 기술적으로 구현이 가능한지 확인해봅니다.
> 
> 불가능 하다면, 기획을 다시 해야하고,
> 가능하다면, 어떤 부분을 더 고민해봐야 하는지 확인합니다.
> 
> * [x]  메일서버 구축
> * [x]  메일 받기
> * [x]  메일 보내기
> * [x]  받은 메일 파싱
> * [x]  dns설정
> * [x]  tls
> * [x]  Mail Account DB연동
> * [ ]  메일 서버로 메일이 왔을 때 DB에 등록
> * [ ]  주소록 검색알고리즘
> * [ ]  dovecot pop3, imap server연결

**Comment by ljh1324** [comment]
> > 기술적으로 구현이 가능한지 확인해봅니다.
> > 불가능 하다면, 기획을 다시 해야하고,
> > 가능하다면, 어떤 부분을 더 고민해봐야 하는지 확인합니다.
> > 
> > * [x]   메일서버 구축
> > * [x]   메일 받기
> > * [x]   메일 보내기
> > * [x]   받은 메일 파싱
> > * [x]   dns설정
> > * [x]   tls
> > * [x]   Mail Account DB연동
> > * [x]   메일 서버로 메일이 왔을 때 DB에 등록
> > * [x]   주소록 검색알고리즘
> > * [ ]   dovecot pop3, imap server연결

**Comment by sjh2428** [comment]
> > > 기술적으로 구현이 가능한지 확인해봅니다.
> > > 불가능 하다면, 기획을 다시 해야하고,
> > > 가능하다면, 어떤 부분을 더 고민해봐야 하는지 확인합니다.
> > > 
> > > * [x]    메일서버 구축
> > > * [x]    메일 받기
> > > * [x]    메일 보내기
> > > * [x]    받은 메일 파싱
> > > * [x]    dns설정
> > > * [x]    tls
> > > * [x]    Mail Account DB연동
> > > * [x]    메일 서버로 메일이 왔을 때 DB에 등록
> > > * [x]    주소록 검색알고리즘
> > > * [x]    dovecot pop3, imap server연결
